[package]
name = 'rust_bc_pos'
version = '0.1.0'
edition = '2021'

[dependencies]
tokio = '1.15.0'
clap = { version = "3.0.10", features = ["derive"] }

[dependencies.server]
path = './libs/server'


[dependencies.p2p_server]
path = './libs/p2p_server'
