[package]
name = 'rust_bc_pos'
version = '0.1.0'
edition = '2021'
[global.limits]
json = 5242880

[dependencies]
tokio = '1.15.0'

[dependencies.server]
path = './libs/server'


[dependencies.websockets]
path = './libs/websockets'
